name: Run Puppeteer Script

on:
  push:
    branches:
      - main  # Ejecuta el workflow cuando se hace push a la rama main
  workflow_dispatch:  # Permite ejecutar el workflow manualmente
  schedule:
    - cron: '*/5 * * * *'  # Ejecuta el workflow cada 5 minutos

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Usa una versión de Node.js compatible con Puppeteer

      - name: Install dependencies
        run: npm install

      - name: Run Puppeteer script
        run: npm start
