name: Run Puppeteer Script

on:
  push:
    branches:
      - main  # Se ejecutará cuando se haga un push en la rama principal
  workflow_dispatch:  # Permite ejecutar manualmente desde la interfaz de GitHub
  schedule:
    - cron: '*/5 * * * *'  # Ejecuta cada 5 minutos

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Utiliza una versión estable de actions/checkout

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Usa la versión de Node.js que prefieras, o la que sea compatible con tu proyecto

      - name: Install dependencies
        run: npm install  # Instala las dependencias del proyecto

      - name: Install Puppeteer Extra Plugins
        run: npm install puppeteer-extra puppeteer-extra-plugin-stealth  # Instala los plugins necesarios

      - name: Run Puppeteer script
        run: node script.js  # Ejecuta tu script Puppeteer
