name: Renew Button

on:
  schedule:
    # Ejecutar cada 50 minutos
    - cron: '*/50 * * * *'

jobs:
  renew:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install selenium webdriver-manager

    - name: Run renew_button.py
      env:
        MC_USERNAME: ${{ secrets.MC_USERNAME }}
        MC_PASSWORD: ${{ secrets.MC_PASSWORD }}
      run: python renew_button.py
