name: Run Puppeteer Script

on:
  schedule:
    - cron: '*/5 * * * *'  # Ejecutar cada 5 minutos
  workflow_dispatch:  # Permite ejecutar manualmente el workflow

jobs:
  run-script:
    runs-on: ubuntu-latest  # Usar la última versión de Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Verifica el código fuente del repositorio

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgbm-dev \
            wget \
            unzip \
            fontconfig \
            locales \
            libasound2t64 \
            libatk1.0-0 \
            libc6 \
            libcairo2 \
            libcups2 \
            libdbus-1-3 \
            libexpat1 \
            libfontconfig1 \
            libgcc1 \
            libgdk-pixbuf2.0-0 \
            libglib2.0-0 \
            libgtk-3-0 \
            libnspr4 \
            libpango-1.0-0 \
            libpangocairo-1.0-0 \
            libstdc++6 \
            libx11-6 \
            libx11-xcb1 \
            libxcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxext6 \
            libxfixes3 \
            libxi6 \
            libxrandr2 \
            libxrender1 \
            libxss1 \
            libxtst6 \
            ca-certificates \
            fonts-liberation \
            libnss3 \
            lsb-release \
            xdg-utils

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Usa la versión de Node.js que prefieras

      - name: Install puppeteer dependencies
        run: |
          npm install puppeteer-extra puppeteer-extra-plugin-stealth
          npm install puppeteer

      - name: Run Puppeteer script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: node script.js  # Asegúrate de que el archivo se llame 'script.js' o el nombre correcto

