name: Run Puppeteer Script

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Ejecuta cada 5 minutos

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Install Puppeteer Extra Plugins
        run: npm install puppeteer-extra puppeteer-extra-plugin-stealth

      - name: Run Puppeteer script
        run: node script.js
